server:
  port: 8001
spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    host: /
    connection-timeout: 15000
    publisher-confirms: true # 是否确认消息确认模式
    # publisher-returns: true # 设置return消息模式 注意要和mandatory一起配合使用
    # template:
    #  mandatory: true

